server:
  port: 9000
spring:
  application:
    name: customer-platform
  datasource:
    url: jdbc:mysql://rm-2ze6c7owydb4e8akk8o.mysql.rds.aliyuncs.com:3306/minibank?useUnicode=true&characterEncoding=utf8
    username: minibank
    password: LiuLei123qwe
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.154.223:8848,81.70.218.187:8848,81.70.224.5:8848
        username: nacos
        password: nacos

dubbo:
  scan:
    base-packages: com.minibank.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost