server:
  port: 9100
spring:
  application:
    name: deposit-service
  datasource:
    url: jdbc:mysql://rm-2ze6c7owydb4e8akk8o.mysql.rds.aliyuncs.com:3306/minibank?useUnicode=true&characterEncoding=utf8
    username: minibank
    password: LiuLei123qwe
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.154.223:8848,81.70.218.187:8848,81.70.224.5:8848
        username: nacos
        password: nacos
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8719
#      datasource:
#        # 自定义的流控规则数据源名称
#        flow:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            username: nacos
#            password: nacos
#            data-id: ${spring.application.name}-flow-rules
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow
dubbo:
  scan:
    base-packages: com.minibank.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost